# Generated by Django 4.2.16 on 2024-11-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_content_af_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='author',
            name='about_ar',
        ),
        migrations.RemoveField(
            model_name='author',
            name='about_short_ar',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='about_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='about_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='about_short',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='about_short_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='about_short_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
